spring:
  profiles: dev
  jpa:
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    properties:
      hibernate:
        format: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #    generate-ddl: true
    #    show-sql: true
    database: POSTGRESQL
  #    hibernate:
  #      ddl-auto: create
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace
systemProp:
  sonar:
    projectKey: ecommurz-be
    organization : portfo-research
    host:
      url: https://sonarcloud.io
