name: Pipeline
on:
  pull_request:
    branches:
      - master
      - dev
permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Jacoco
        run: ./gradlew jacocoTestReport

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info --args='--spring.profiles.active=local'